import {
  AccountCircle,
  ArticleOutlined,
  BookmarksOutlined,
  DashboardCustomizeOutlined,
  Logout,
  Mail,
  Menu,
  MoreVert,
  NoteAltOutlined,
  Notifications,
  PermIdentity,
  Search,
  Settings,
  Close,
  FavoriteBorder,
  Favorite,
  Comment,
  BookmarkAddOutlined,
  BookmarkOutlined,
  MoreHoriz,
} from '@mui/icons-material';

const Icons = {
  AccountCircle,
  ArticleOutlined,
  BookmarksOutlined,
  DashboardCustomizeOutlined,
  Logout,
  Mail,
  Menu,
  MoreVert,
  NoteAltOutlined,
  Notifications,
  PermIdentity,
  Search,
  Settings,
  Close,
  FavoriteBorder,
  Favorite,
  Comment,
  BookmarkAddOutlined,
  BookmarkOutlined,
  MoreHoriz,
};

export default Icons;
